### PR TITLE
Remove TODO for implementing `__iter__`

### PR DESCRIPTION
**Pull request by francium**
Cleans up the todo to implement the `__iter__`. Hopefully this is what you meant by that todo. Otherwise let me know and we can fix it up.

### CODE REVIEW

**Comment by dbrgn** [comment]
> Hopefully this is what you meant by that todo.

Hehe, I actually can't remember :slightly_smiling_face: 

I'm not sure what the best approach for iteration would be. Do you think this makes sense in the context of Python? Do you have a possible use case?

In Rust, the iter() method "Returns an iterator over the possibly contained value, the iterator yields one value if the result is Result::Ok, otherwise none".

**Comment by francium** [comment]
The unwrapping into a tuple I think might make sense, `(err, ok) = result`. Seems pythonic enough. I think `golang` has a similar approach, but I don't know how applicable what's typical in `golang` is here. Use case for it? Maybe interoping with non-result code?

But honestly I've been away from any serious Python (and Rust as well) work for a while so I'm not 100% confident here.

Maybe we can close this PR then if it's currently not very useful in your opinion and reopen/revisit should the need come up in the future. Or maybe just use this PR to remove the TODO?

**Comment by dbrgn** [comment]
> Or maybe just use this PR to remove the TODO?

Yes, that would be great! I don't think we should merge it unless there's a clear use case that cannot be solved in a better way using other already existing methods.

**Comment by francium** [comment]
Sounds like the right decision. PR now only contains removal of TODO comment.

**Pull request merged**
