### PR TITLE
__eq__ magic method

### PR DESCRIPTION
**Pull request by iwtcs**
Happy to see this module exists.
I was toying with it the other day and felt I could make my code simpler using a bit of chaining.
So here are the [and_then](https://doc.rust-lang.org/std/result/enum.Result.html#method.and_then) and [or_else}(https://doc.rust-lang.org/std/result/enum.Result.html#method.or_else) inspired methods.

I added the kwargs option for more flexibility (and clarity)

I also added the __eq__  magic method as Ok(1) was not equal to Ok(1)

### CODE REVIEW

**Comment by dbrgn** [comment]
Hi. Thanks for your PR!

I like the `__eq__` implementation, missed that. Thanks for noting.

On the other hand, I'm not sure about the `and_then` and `or_else` methods. To me, they seem to make code unpythonic and harder to read, while not bringing any additional benefits regarding type safety.

Could you show a concrete example where you think the methods make code easier to read or more safe?

**Comment by iwtcs** [comment]
I thought about it and agree with you, if the goal was to be an exact replica of the rust implementation it would be ok but keeping it pythonic makes more sense.

I left the __eq__ stuff though.

cheers

**Comment by iwtcs** [comment]
_just meant to comment_

**Comment by dbrgn** [comment]
Cool, thanks!

**Comment by dbrgn** [comment]
Version 0.2.2 is released containing your fix.

**Pull request merged**
