### PR TITLE
Drop support for Python3.5, add support for Python3.6, bump mypy version

### LINKED ISSUE #34: Bump min python version - Python 3.5 end of support
[End of support for Python 3.5 is 2020-09-13](https://www.python.org/downloads/).

### PR DESCRIPTION
**Pull request by francium**
Fixed #34

### CODE REVIEW

**Comment by francium** [comment]
@dbrgn The test runner is saying,

> Python 3.5 Expected — Waiting for status to be reported

Any idea what's going on there?

**Comment by dbrgn** [comment]
Cool, thanks! However, do you think it's worthwhile to create a new release with just this change? I think I'd simply drop 3.5 support on master and wait until we have a few changes that make a new release worthwhile.

> Any idea what's going on there?

Fixed. Yeah, it's the "CI steps that need to pass for a merge" setting.

**Comment by francium** [comment]
> do you think it's worthwhile to create a new release with just this change? I think I'd simply drop 3.5 support on master and wait until we have a few changes that make a new release worthwhile.

That sounds good. I didn't really intend a new release, just wasn't sure. I'll make the change.

Thanks

**Comment by francium** [comment]
...well what changes should I undo if we're not releasing? Do you want to keep the `0.7.0-rc.1` in setup.py and CHANGELOG.md?

**Comment by dbrgn** [comment]
I'd just remove the date and version number in the CHANGELOG and replace it with "Unreleased", I think that's all 🙂 And maybe `0.7.0-dev` in setup.py?

**Review by dbrgn — APPROVED** [review]
Thanks!

**Pull request merged**
